name: SpotBrief
options:
  bundleIdPrefix: com.winmatwey
  xcodeVersion: "15.0" # Это заставит проект открыться в Xcode 15.4
targets:
  SpotBrief:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/SpotBrief
    info:
      plist:
        CFBundleDevelopmentRegion: en
        CFBundleIdentifier: com.winmatwey.SpotBrief
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
    settings:
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: NO
